// Demo data shaped to match Supabase query return format for client presentations.
// Used when NEXT_PUBLIC_DEMO_MODE=true

const NOW = "2026-05-23T10:00:00Z";

export const DEMO_PROFILE = {
  id: "demo-profile-1",
  auth_user_id: "demo-user-1",
  full_name: "Nouman Ejaz",
  email: "nouman@autoplay.ai",
  role: "admin" as const,
  job_title: "Founder & Lead Engineer",
  department: "Engineering",
  profile_photo_url: null,
  phone: "+1 514-555-0100",
  timezone: "EST",
  location: "Montreal, QC",
  bio: "Founder of Autoplay. Builds AI-powered systems for client automation and lead generation.",
  skills: ["AI/ML", "Next.js", "Python", "n8n", "Supabase"],
  years_experience: 6,
  certifications: ["AWS Solutions Architect"],
  linkedin_url: "https://linkedin.com/in/nouman",
  portfolio_url: null,
  availability_status: "Busy" as const,
  is_active: true,
  created_at: "2026-01-01T00:00:00Z",
  updated_at: NOW,
};

export const DEMO_CLIENTS = [
  {
    id: "cl1", company_name: "Tongal Media", contact_person_name: "Tommy Chen",
    contact_email: "tommy@tongal.com", contact_phone: "+1 310-555-0142",
    whatsapp: "+1 310-555-0142", timezone: "PST",
    preferred_channel: "WhatsApp" as const, industry: "Media & Entertainment",
    website: "https://tongal.com", project_owner_id: "demo-profile-1",
    priority: "High" as const, status: "Active" as const, health_status: "Good" as const,
    internal_notes: "High priority. Very responsive on WhatsApp.",
    drive_folder_url: null, created_by: "demo-profile-1",
    created_at: "2026-03-01T00:00:00Z", updated_at: NOW,
    owner: { id: "demo-profile-1", full_name: "Nouman Ejaz", profile_photo_url: null },
  },
  {
    id: "cl2", company_name: "Global Supplier Outreach", contact_person_name: "Robert Williams",
    contact_email: "robert@globalsupplier.co", contact_phone: null,
    whatsapp: null, timezone: "EST",
    preferred_channel: "Email" as const, industry: "B2B / Wholesale",
    website: "https://globalsupplier.co", project_owner_id: "demo-profile-1",
    priority: "High" as const, status: "Active" as const, health_status: "Healthy" as const,
    internal_notes: null, drive_folder_url: null, created_by: "demo-profile-1",
    created_at: "2026-02-15T00:00:00Z", updated_at: NOW,
    owner: { id: "demo-profile-1", full_name: "Nouman Ejaz", profile_photo_url: null },
  },
  {
    id: "cl3", company_name: "MedReach Clinics", contact_person_name: "Dr. Steve Hartman",
    contact_email: "steve@medreach.clinic", contact_phone: "+1 905-555-0198",
    whatsapp: null, timezone: "EST",
    preferred_channel: "Zoom" as const, industry: "Healthcare",
    website: "https://medreach.clinic", project_owner_id: "demo-profile-2",
    priority: "Urgent" as const, status: "Active" as const, health_status: "At Risk" as const,
    internal_notes: "Slow to respond. Follow up via phone if email ignored.",
    drive_folder_url: null, created_by: "demo-profile-1",
    created_at: "2026-04-01T00:00:00Z", updated_at: NOW,
    owner: { id: "demo-profile-2", full_name: "Zara Khan", profile_photo_url: null },
  },
  {
    id: "cl4", company_name: "FrankBot Solutions", contact_person_name: "Frank Okonkwo",
    contact_email: "frank@frankbot.io", contact_phone: null,
    whatsapp: null, timezone: "WAT",
    preferred_channel: "Telegram" as const, industry: "Tech / SaaS",
    website: "https://frankbot.io", project_owner_id: "demo-profile-5",
    priority: "Medium" as const, status: "Active" as const, health_status: "Healthy" as const,
    internal_notes: null, drive_folder_url: null, created_by: "demo-profile-1",
    created_at: "2026-01-10T00:00:00Z", updated_at: NOW,
    owner: { id: "demo-profile-5", full_name: "Bilal Siddiqui", profile_photo_url: null },
  },
  {
    id: "cl5", company_name: "BuildRight Construction", contact_person_name: "James Patterson",
    contact_email: "james@buildright.com", contact_phone: null,
    whatsapp: "+1 403-555-0188", timezone: "MST",
    preferred_channel: "WhatsApp" as const, industry: "Construction",
    website: "https://buildright.com", project_owner_id: "demo-profile-5",
    priority: "Medium" as const, status: "Active" as const, health_status: "Good" as const,
    internal_notes: null, drive_folder_url: null, created_by: "demo-profile-1",
    created_at: "2026-03-20T00:00:00Z", updated_at: NOW,
    owner: { id: "demo-profile-5", full_name: "Bilal Siddiqui", profile_photo_url: null },
  },
  {
    id: "cl6", company_name: "ScaleUp Ventures", contact_person_name: "Dean Martinez",
    contact_email: "dean@scaleup.vc", contact_phone: "+1 512-555-0177",
    whatsapp: null, timezone: "CST",
    preferred_channel: "Slack" as const, industry: "Venture Capital",
    website: "https://scaleup.vc", project_owner_id: "demo-profile-1",
    priority: "High" as const, status: "In The Talk" as const, health_status: "Healthy" as const,
    internal_notes: null, drive_folder_url: null, created_by: "demo-profile-1",
    created_at: "2026-05-10T00:00:00Z", updated_at: NOW,
    owner: { id: "demo-profile-1", full_name: "Nouman Ejaz", profile_photo_url: null },
  },
];

const DEMO_MEMBERS_PR1 = [
  { user_id: "demo-profile-1", project_role: "Manager", profile: { id: "demo-profile-1", full_name: "Nouman Ejaz", profile_photo_url: null } },
  { user_id: "demo-profile-5", project_role: "Developer", profile: { id: "demo-profile-5", full_name: "Bilal Siddiqui", profile_photo_url: null } },
];

export const DEMO_PROJECTS = [
  {
    id: "pr1", client_id: "cl1", project_name: "OpenClaw Lead Pipeline",
    description: "Automated lead extraction and ingestion via OpenClaw gateway with Apollo enrichment",
    project_type: "Lead Generation", start_date: "2026-03-01",
    expected_due_date: "2026-06-15", actual_completion_date: null,
    status: "Active", priority: "High" as const, progress_percentage: 68,
    project_manager_id: "demo-profile-1", estimated_hours: 120, budget: 8500,
    tags: ["lead-gen", "openclaw", "apollo"], internal_notes: null,
    overdue_reason: null, employee_category: "Lead Generation",
    created_by: "demo-profile-1", created_at: "2026-03-01T00:00:00Z", updated_at: NOW,
    client: { id: "cl1", company_name: "Tongal Media", contact_person_name: "Tommy Chen" },
    manager: { id: "demo-profile-1", full_name: "Nouman Ejaz", profile_photo_url: null },
    members: DEMO_MEMBERS_PR1,
  },
  {
    id: "pr2", client_id: "cl2", project_name: "Supplier Email Automation",
    description: "Automated email outreach to 5000+ suppliers with response tracking",
    project_type: "Email Automation", start_date: "2026-02-15",
    expected_due_date: "2026-05-31", actual_completion_date: null,
    status: "Active", priority: "High" as const, progress_percentage: 82,
    project_manager_id: "demo-profile-1", estimated_hours: 80, budget: 6200,
    tags: ["email", "smtp", "outreach"], internal_notes: null,
    overdue_reason: null, employee_category: "Outreach",
    created_by: "demo-profile-1", created_at: "2026-02-15T00:00:00Z", updated_at: NOW,
    client: { id: "cl2", company_name: "Global Supplier Outreach", contact_person_name: "Robert Williams" },
    manager: { id: "demo-profile-1", full_name: "Nouman Ejaz", profile_photo_url: null },
    members: [
      { user_id: "demo-profile-1", project_role: "Manager", profile: { id: "demo-profile-1", full_name: "Nouman Ejaz", profile_photo_url: null } },
      { user_id: "demo-profile-4", project_role: "Frontend", profile: { id: "demo-profile-4", full_name: "Aisha Malik", profile_photo_url: null } },
    ],
  },
  {
    id: "pr3", client_id: "cl3", project_name: "MedReach Email System",
    description: "Patient communication email system with appointment reminders and follow-ups",
    project_type: "Email System", start_date: "2026-04-01",
    expected_due_date: "2026-06-30", actual_completion_date: null,
    status: "On Hold", priority: "Urgent" as const, progress_percentage: 35,
    project_manager_id: "demo-profile-2", estimated_hours: 100, budget: 4800,
    tags: ["email", "healthcare", "automation"], internal_notes: null,
    overdue_reason: null, employee_category: "Infrastructure",
    created_by: "demo-profile-1", created_at: "2026-04-01T00:00:00Z", updated_at: NOW,
    client: { id: "cl3", company_name: "MedReach Clinics", contact_person_name: "Dr. Steve Hartman" },
    manager: { id: "demo-profile-2", full_name: "Zara Khan", profile_photo_url: null },
    members: [
      { user_id: "demo-profile-2", project_role: "Manager", profile: { id: "demo-profile-2", full_name: "Zara Khan", profile_photo_url: null } },
      { user_id: "demo-profile-1", project_role: "Lead", profile: { id: "demo-profile-1", full_name: "Nouman Ejaz", profile_photo_url: null } },
    ],
  },
  {
    id: "pr4", client_id: "cl4", project_name: "Telegram Bot Fleet",
    description: "3 Telegram bots with AI responses, admin panel, and webhook delivery pipeline",
    project_type: "Bot Development", start_date: "2026-01-10",
    expected_due_date: "2026-05-30", actual_completion_date: null,
    status: "Active", priority: "Medium" as const, progress_percentage: 91,
    project_manager_id: "demo-profile-5", estimated_hours: 100, budget: 12000,
    tags: ["telegram", "bots", "ai"], internal_notes: null,
    overdue_reason: null, employee_category: "AI Automation",
    created_by: "demo-profile-1", created_at: "2026-01-10T00:00:00Z", updated_at: NOW,
    client: { id: "cl4", company_name: "FrankBot Solutions", contact_person_name: "Frank Okonkwo" },
    manager: { id: "demo-profile-5", full_name: "Bilal Siddiqui", profile_photo_url: null },
    members: [
      { user_id: "demo-profile-5", project_role: "Manager", profile: { id: "demo-profile-5", full_name: "Bilal Siddiqui", profile_photo_url: null } },
      { user_id: "demo-profile-2", project_role: "AI Engineer", profile: { id: "demo-profile-2", full_name: "Zara Khan", profile_photo_url: null } },
      { user_id: "demo-profile-4", project_role: "Frontend", profile: { id: "demo-profile-4", full_name: "Aisha Malik", profile_photo_url: null } },
    ],
  },
  {
    id: "pr5", client_id: "cl5", project_name: "BuildRight n8n Automation",
    description: "n8n workflow automation for construction project management",
    project_type: "Workflow Automation", start_date: "2026-03-20",
    expected_due_date: "2026-06-20", actual_completion_date: null,
    status: "Active", priority: "Medium" as const, progress_percentage: 55,
    project_manager_id: "demo-profile-5", estimated_hours: 90, budget: 5500,
    tags: ["n8n", "automation", "vps"], internal_notes: null,
    overdue_reason: null, employee_category: "Infrastructure",
    created_by: "demo-profile-1", created_at: "2026-03-20T00:00:00Z", updated_at: NOW,
    client: { id: "cl5", company_name: "BuildRight Construction", contact_person_name: "James Patterson" },
    manager: { id: "demo-profile-5", full_name: "Bilal Siddiqui", profile_photo_url: null },
    members: [
      { user_id: "demo-profile-5", project_role: "Manager", profile: { id: "demo-profile-5", full_name: "Bilal Siddiqui", profile_photo_url: null } },
      { user_id: "demo-profile-3", project_role: "DevOps", profile: { id: "demo-profile-3", full_name: "Omar Farooq", profile_photo_url: null } },
    ],
  },
  {
    id: "pr6", client_id: "cl6", project_name: "ScaleUp Lead Gen Setup",
    description: "Full lead generation infrastructure with Apollo, ZoomInfo, and outreach automation",
    project_type: "Lead Generation", start_date: "2026-05-10",
    expected_due_date: "2026-07-31", actual_completion_date: null,
    status: "Planning", priority: "High" as const, progress_percentage: 15,
    project_manager_id: "demo-profile-1", estimated_hours: 120, budget: 9000,
    tags: ["lead-gen", "apollo", "zoominfo"], internal_notes: null,
    overdue_reason: null, employee_category: "Lead Generation",
    created_by: "demo-profile-1", created_at: "2026-05-10T00:00:00Z", updated_at: NOW,
    client: { id: "cl6", company_name: "ScaleUp Ventures", contact_person_name: "Dean Martinez" },
    manager: { id: "demo-profile-1", full_name: "Nouman Ejaz", profile_photo_url: null },
    members: [
      { user_id: "demo-profile-1", project_role: "Manager", profile: { id: "demo-profile-1", full_name: "Nouman Ejaz", profile_photo_url: null } },
      { user_id: "demo-profile-5", project_role: "Automation", profile: { id: "demo-profile-5", full_name: "Bilal Siddiqui", profile_photo_url: null } },
      { user_id: "demo-profile-3", project_role: "DevOps", profile: { id: "demo-profile-3", full_name: "Omar Farooq", profile_photo_url: null } },
    ],
  },
];

export const DEMO_TASKS = [
  {
    id: "t1", project_id: "pr1", client_id: "cl1",
    title: "Integrate LinkedIn Sales Navigator export to OpenClaw pipeline",
    description: "Once LinkedIn access received, build the export → parse → ingest pipeline",
    assigned_to: "demo-profile-1", created_by: "demo-profile-1",
    status: "Waiting on Client", priority: "High" as const,
    due_date: "2026-05-30", estimated_hours: 8,
    client_visible: false, internal_only: true, tags: ["linkedin", "openclaw"],
    created_at: "2026-05-10T00:00:00Z", updated_at: NOW, completed_at: null,
    assignee: { id: "demo-profile-1", full_name: "Nouman Ejaz", profile_photo_url: null },
    project: { id: "pr1", project_name: "OpenClaw Lead Pipeline" },
    client: { id: "cl1", company_name: "Tongal Media" },
  },
  {
    id: "t2", project_id: "pr2", client_id: "cl2",
    title: "Final testing of supplier email sequences",
    description: "Run full end-to-end test with 50 test suppliers before go-live",
    assigned_to: "demo-profile-1", created_by: "demo-profile-1",
    status: "In Progress", priority: "High" as const,
    due_date: "2026-05-25", estimated_hours: 6,
    client_visible: false, internal_only: true, tags: ["testing", "email"],
    created_at: "2026-05-12T00:00:00Z", updated_at: NOW, completed_at: null,
    assignee: { id: "demo-profile-1", full_name: "Nouman Ejaz", profile_photo_url: null },
    project: { id: "pr2", project_name: "Supplier Email Automation" },
    client: { id: "cl2", company_name: "Global Supplier Outreach" },
  },
  {
    id: "t3", project_id: "pr3", client_id: "cl3",
    title: "SMTP setup for MedReach",
    description: "Configure SMTP with Dr. Steve's credentials once received",
    assigned_to: "demo-profile-2", created_by: "demo-profile-1",
    status: "Blocked", priority: "Critical" as const,
    due_date: "2026-05-20", estimated_hours: 4,
    client_visible: false, internal_only: true, tags: ["smtp", "blocked"],
    created_at: "2026-05-01T00:00:00Z", updated_at: NOW, completed_at: null,
    assignee: { id: "demo-profile-2", full_name: "Zara Khan", profile_photo_url: null },
    project: { id: "pr3", project_name: "MedReach Email System" },
    client: { id: "cl3", company_name: "MedReach Clinics" },
  },
  {
    id: "t4", project_id: "pr4", client_id: "cl4",
    title: "Deploy Telegram admin panel to production",
    description: "Final production deployment of the FrankBot admin interface",
    assigned_to: "demo-profile-4", created_by: "demo-profile-1",
    status: "In Progress", priority: "Medium" as const,
    due_date: "2026-05-28", estimated_hours: 5,
    client_visible: true, internal_only: false, tags: ["deployment", "admin"],
    created_at: "2026-05-13T00:00:00Z", updated_at: NOW, completed_at: null,
    assignee: { id: "demo-profile-4", full_name: "Aisha Malik", profile_photo_url: null },
    project: { id: "pr4", project_name: "Telegram Bot Fleet" },
    client: { id: "cl4", company_name: "FrankBot Solutions" },
  },
  {
    id: "t5", project_id: "pr5", client_id: "cl5",
    title: "Deploy n8n to BuildRight VPS",
    description: "SSH into VPS, install n8n, configure domain and SSL",
    assigned_to: "demo-profile-3", created_by: "demo-profile-1",
    status: "Waiting on Client", priority: "High" as const,
    due_date: "2026-06-01", estimated_hours: 6,
    client_visible: false, internal_only: true, tags: ["vps", "n8n"],
    created_at: "2026-05-10T00:00:00Z", updated_at: NOW, completed_at: null,
    assignee: { id: "demo-profile-3", full_name: "Omar Farooq", profile_photo_url: null },
    project: { id: "pr5", project_name: "BuildRight n8n Automation" },
    client: { id: "cl5", company_name: "BuildRight Construction" },
  },
  {
    id: "t6", project_id: "pr6", client_id: "cl6",
    title: "Set up Apollo account for ScaleUp",
    description: "Configure Apollo.io with ICP filters and export sequences",
    assigned_to: "demo-profile-5", created_by: "demo-profile-1",
    status: "To Do", priority: "Medium" as const,
    due_date: "2026-06-05", estimated_hours: 4,
    client_visible: true, internal_only: false, tags: ["apollo", "lead-gen"],
    created_at: "2026-05-15T00:00:00Z", updated_at: NOW, completed_at: null,
    assignee: { id: "demo-profile-5", full_name: "Bilal Siddiqui", profile_photo_url: null },
    project: { id: "pr6", project_name: "ScaleUp Lead Gen Setup" },
    client: { id: "cl6", company_name: "ScaleUp Ventures" },
  },
  {
    id: "t7", project_id: "pr4", client_id: "cl4",
    title: "Write handover documentation for Telegram bots",
    description: "Create full handover doc including bot commands and admin panel guide",
    assigned_to: "demo-profile-5", created_by: "demo-profile-1",
    status: "To Do", priority: "Low" as const,
    due_date: "2026-05-30", estimated_hours: 3,
    client_visible: true, internal_only: false, tags: ["documentation"],
    created_at: "2026-05-14T00:00:00Z", updated_at: NOW, completed_at: null,
    assignee: { id: "demo-profile-5", full_name: "Bilal Siddiqui", profile_photo_url: null },
    project: { id: "pr4", project_name: "Telegram Bot Fleet" },
    client: { id: "cl4", company_name: "FrankBot Solutions" },
  },
  {
    id: "t8", project_id: "pr1", client_id: "cl1",
    title: "Autoplay internal dashboard build",
    description: "Build the Autoplay internal ClientOps platform",
    assigned_to: "demo-profile-4", created_by: "demo-profile-1",
    status: "In Progress", priority: "High" as const,
    due_date: "2026-05-31", estimated_hours: 40,
    client_visible: false, internal_only: true, tags: ["internal", "dashboard"],
    created_at: "2026-05-01T00:00:00Z", updated_at: NOW, completed_at: null,
    assignee: { id: "demo-profile-4", full_name: "Aisha Malik", profile_photo_url: null },
    project: { id: "pr1", project_name: "OpenClaw Lead Pipeline" },
    client: { id: "cl1", company_name: "Tongal Media" },
  },
  {
    id: "t9", project_id: "pr2", client_id: "cl2",
    title: "Write weekly update for Robert",
    description: null,
    assigned_to: "demo-profile-1", created_by: "demo-profile-1",
    status: "Completed", priority: "Low" as const,
    due_date: "2026-05-15", estimated_hours: 1,
    client_visible: true, internal_only: false, tags: ["communication"],
    created_at: "2026-05-14T00:00:00Z", updated_at: NOW, completed_at: "2026-05-15T09:00:00Z",
    assignee: { id: "demo-profile-1", full_name: "Nouman Ejaz", profile_photo_url: null },
    project: { id: "pr2", project_name: "Supplier Email Automation" },
    client: { id: "cl2", company_name: "Global Supplier Outreach" },
  },
];

export const DEMO_TIME_LOGS = [
  {
    id: "tl1", user_id: "demo-profile-1", client_id: "cl1", project_id: "pr1", task_id: "t1",
    work_date: "2026-05-22", hours: 3, work_description: "Pipeline architecture review and LinkedIn API docs research",
    category: "Research", billable: true, approved: true, approved_by: null,
    created_at: "2026-05-22T18:00:00Z", updated_at: NOW,
    user: { id: "demo-profile-1", full_name: "Nouman Ejaz", profile_photo_url: null },
    project: { id: "pr1", project_name: "OpenClaw Lead Pipeline" },
    client: { id: "cl1", company_name: "Tongal Media" },
    task: { id: "t1", title: "LinkedIn integration planning" },
  },
  {
    id: "tl2", user_id: "demo-profile-1", client_id: "cl2", project_id: "pr2", task_id: "t2",
    work_date: "2026-05-22", hours: 2, work_description: "End-to-end test run with 50 test emails",
    category: "Testing", billable: true, approved: true, approved_by: null,
    created_at: "2026-05-22T20:00:00Z", updated_at: NOW,
    user: { id: "demo-profile-1", full_name: "Nouman Ejaz", profile_photo_url: null },
    project: { id: "pr2", project_name: "Supplier Email Automation" },
    client: { id: "cl2", company_name: "Global Supplier Outreach" },
    task: { id: "t2", title: "Email sequence testing" },
  },
  {
    id: "tl3", user_id: "demo-profile-2", client_id: "cl3", project_id: "pr3", task_id: null,
    work_date: "2026-05-22", hours: 2, work_description: "Follow-up with Dr. Steve on SMTP credentials.",
    category: "Communication", billable: true, approved: false, approved_by: null,
    created_at: "2026-05-22T17:00:00Z", updated_at: NOW,
    user: { id: "demo-profile-2", full_name: "Zara Khan", profile_photo_url: null },
    project: { id: "pr3", project_name: "MedReach Email System" },
    client: { id: "cl3", company_name: "MedReach Clinics" },
    task: null,
  },
  {
    id: "tl4", user_id: "demo-profile-4", client_id: "cl4", project_id: "pr4", task_id: "t4",
    work_date: "2026-05-21", hours: 3, work_description: "Production build and deployment of admin panel",
    category: "Deployment", billable: true, approved: false, approved_by: null,
    created_at: "2026-05-21T19:00:00Z", updated_at: NOW,
    user: { id: "demo-profile-4", full_name: "Aisha Malik", profile_photo_url: null },
    project: { id: "pr4", project_name: "Telegram Bot Fleet" },
    client: { id: "cl4", company_name: "FrankBot Solutions" },
    task: { id: "t4", title: "Admin panel deployment" },
  },
  {
    id: "tl5", user_id: "demo-profile-5", client_id: "cl5", project_id: "pr5", task_id: null,
    work_date: "2026-05-21", hours: 4, work_description: "n8n form submission workflow build and testing",
    category: "Development", billable: true, approved: true, approved_by: null,
    created_at: "2026-05-21T18:00:00Z", updated_at: NOW,
    user: { id: "demo-profile-5", full_name: "Bilal Siddiqui", profile_photo_url: null },
    project: { id: "pr5", project_name: "BuildRight n8n Automation" },
    client: { id: "cl5", company_name: "BuildRight Construction" },
    task: null,
  },
  {
    id: "tl6", user_id: "demo-profile-3", client_id: "cl6", project_id: "pr6", task_id: null,
    work_date: "2026-05-21", hours: 2, work_description: "Infrastructure planning for ScaleUp lead gen stack",
    category: "Planning", billable: true, approved: false, approved_by: null,
    created_at: "2026-05-21T20:00:00Z", updated_at: NOW,
    user: { id: "demo-profile-3", full_name: "Omar Farooq", profile_photo_url: null },
    project: { id: "pr6", project_name: "ScaleUp Lead Gen Setup" },
    client: { id: "cl6", company_name: "ScaleUp Ventures" },
    task: null,
  },
  {
    id: "tl7", user_id: "demo-profile-1", client_id: "cl6", project_id: "pr6", task_id: null,
    work_date: "2026-05-20", hours: 3, work_description: "Kickoff call with Dean, ICP documentation, project scoping",
    category: "Meeting", billable: true, approved: true, approved_by: null,
    created_at: "2026-05-20T18:00:00Z", updated_at: NOW,
    user: { id: "demo-profile-1", full_name: "Nouman Ejaz", profile_photo_url: null },
    project: { id: "pr6", project_name: "ScaleUp Lead Gen Setup" },
    client: { id: "cl6", company_name: "ScaleUp Ventures" },
    task: null,
  },
];

export const DEMO_ASSETS = [
  {
    id: "a1", client_id: "cl1", project_id: "pr1",
    title: "Tongal Lead Database", description: "Contains 10,000 leads. Do not share externally.",
    asset_type: "Google Sheet", file_url: null, external_url: "https://sheets.google.com/tongal-leads",
    uploaded_by: "demo-profile-1", provided_by_client: true,
    visibility: "Internal" as const, is_pinned: true, tags: ["leads", "database"],
    created_at: "2026-03-05T00:00:00Z", updated_at: NOW,
    client: { id: "cl1", company_name: "Tongal Media" },
    project: { id: "pr1", project_name: "OpenClaw Lead Pipeline" },
    uploader: { id: "demo-profile-1", full_name: "Nouman Ejaz" },
  },
  {
    id: "a2", client_id: "cl1", project_id: "pr1",
    title: "Project Brief - OpenClaw", description: null,
    asset_type: "Google Doc", file_url: null, external_url: "https://docs.google.com/openclaw-brief",
    uploaded_by: "demo-profile-1", provided_by_client: true,
    visibility: "Internal" as const, is_pinned: false, tags: ["brief", "requirements"],
    created_at: "2026-03-01T00:00:00Z", updated_at: NOW,
    client: { id: "cl1", company_name: "Tongal Media" },
    project: { id: "pr1", project_name: "OpenClaw Lead Pipeline" },
    uploader: { id: "demo-profile-1", full_name: "Nouman Ejaz" },
  },
  {
    id: "a3", client_id: "cl2", project_id: "pr2",
    title: "Supplier Master List", description: "5,280 suppliers. Cleaned and deduped as of March 2026.",
    asset_type: "Google Sheet", file_url: null, external_url: "https://sheets.google.com/supplier-list",
    uploaded_by: "demo-profile-1", provided_by_client: true,
    visibility: "Internal" as const, is_pinned: true, tags: ["suppliers", "outreach"],
    created_at: "2026-02-20T00:00:00Z", updated_at: NOW,
    client: { id: "cl2", company_name: "Global Supplier Outreach" },
    project: { id: "pr2", project_name: "Supplier Email Automation" },
    uploader: { id: "demo-profile-1", full_name: "Nouman Ejaz" },
  },
  {
    id: "a4", client_id: "cl4", project_id: "pr4",
    title: "FrankBot Brand Assets", description: null,
    asset_type: "Brand Assets", file_url: null, external_url: "https://drive.google.com/frankbot-brand",
    uploaded_by: "demo-profile-5", provided_by_client: true,
    visibility: "Client-visible" as const, is_pinned: true, tags: ["branding", "logo"],
    created_at: "2026-01-15T00:00:00Z", updated_at: NOW,
    client: { id: "cl4", company_name: "FrankBot Solutions" },
    project: { id: "pr4", project_name: "Telegram Bot Fleet" },
    uploader: { id: "demo-profile-5", full_name: "Bilal Siddiqui" },
  },
  {
    id: "a5", client_id: "cl6", project_id: "pr6",
    title: "ScaleUp ICP Definition Doc", description: null,
    asset_type: "Google Doc", file_url: null, external_url: "https://docs.google.com/scaleup-icp",
    uploaded_by: "demo-profile-1", provided_by_client: false,
    visibility: "Internal" as const, is_pinned: true, tags: ["icp", "lead-gen", "strategy"],
    created_at: "2026-05-15T00:00:00Z", updated_at: NOW,
    client: { id: "cl6", company_name: "ScaleUp Ventures" },
    project: { id: "pr6", project_name: "ScaleUp Lead Gen Setup" },
    uploader: { id: "demo-profile-1", full_name: "Nouman Ejaz" },
  },
];

export const DEMO_ACCESS_ITEMS = [
  {
    id: "ac1", client_id: "cl1", project_id: "pr1",
    service_name: "LinkedIn Sales Navigator", category: "Lead Generation",
    access_status: "Need Client Action", responsible_user_id: "demo-profile-1",
    secure_location_ref: "Waiting - not yet received",
    login_email: null, access_notes: "Waiting for Tommy to share team seat access",
    action_required: "Client to share LinkedIn team account access",
    last_tested_date: null, priority: "High" as const,
    created_at: "2026-05-01T00:00:00Z", updated_at: NOW,
    client: { id: "cl1", company_name: "Tongal Media" },
    project: { id: "pr1", project_name: "OpenClaw Lead Pipeline" },
    responsible: { id: "demo-profile-1", full_name: "Nouman Ejaz" },
  },
  {
    id: "ac2", client_id: "cl1", project_id: "pr1",
    service_name: "Apollo.io", category: "Lead Generation",
    access_status: "Configured", responsible_user_id: "demo-profile-1",
    secure_location_ref: "1Password - Tongal vault",
    login_email: "tommy@tongal.com", access_notes: "Team account configured. ICP filters set.",
    action_required: null, last_tested_date: "2026-05-10", priority: "High" as const,
    created_at: "2026-03-05T00:00:00Z", updated_at: NOW,
    client: { id: "cl1", company_name: "Tongal Media" },
    project: { id: "pr1", project_name: "OpenClaw Lead Pipeline" },
    responsible: { id: "demo-profile-1", full_name: "Nouman Ejaz" },
  },
  {
    id: "ac3", client_id: "cl3", project_id: "pr3",
    service_name: "SMTP / Email Server", category: "Email",
    access_status: "Pending", responsible_user_id: "demo-profile-2",
    secure_location_ref: "Not received - waiting on client",
    login_email: null, access_notes: "Dr. Steve has not provided SMTP credentials yet",
    action_required: "Follow up with Dr. Steve directly via phone",
    last_tested_date: null, priority: "Critical" as const,
    created_at: "2026-04-01T00:00:00Z", updated_at: NOW,
    client: { id: "cl3", company_name: "MedReach Clinics" },
    project: { id: "pr3", project_name: "MedReach Email System" },
    responsible: { id: "demo-profile-2", full_name: "Zara Khan" },
  },
  {
    id: "ac4", client_id: "cl4", project_id: "pr4",
    service_name: "Telegram Bot Token", category: "Messaging",
    access_status: "Tested", responsible_user_id: "demo-profile-5",
    secure_location_ref: "1Password - FrankBot vault",
    login_email: null, access_notes: "Production token received. Bot is live.",
    action_required: null, last_tested_date: "2026-05-14", priority: "High" as const,
    created_at: "2026-01-15T00:00:00Z", updated_at: NOW,
    client: { id: "cl4", company_name: "FrankBot Solutions" },
    project: { id: "pr4", project_name: "Telegram Bot Fleet" },
    responsible: { id: "demo-profile-5", full_name: "Bilal Siddiqui" },
  },
  {
    id: "ac5", client_id: "cl5", project_id: "pr5",
    service_name: "VPS / Hostinger SSH", category: "Infrastructure",
    access_status: "Need Client Action", responsible_user_id: "demo-profile-3",
    secure_location_ref: "Waiting - not yet received",
    login_email: null, access_notes: "James needs to provide SSH key for BuildRight VPS",
    action_required: "Client to provide VPS SSH access credentials",
    last_tested_date: null, priority: "High" as const,
    created_at: "2026-03-25T00:00:00Z", updated_at: NOW,
    client: { id: "cl5", company_name: "BuildRight Construction" },
    project: { id: "pr5", project_name: "BuildRight n8n Automation" },
    responsible: { id: "demo-profile-3", full_name: "Omar Farooq" },
  },
  {
    id: "ac6", client_id: "cl6", project_id: "pr6",
    service_name: "Apollo.io", category: "Lead Generation",
    access_status: "Pending", responsible_user_id: "demo-profile-5",
    secure_location_ref: "Not received",
    login_email: null, access_notes: "Waiting for Dean to purchase Apollo license",
    action_required: "Dean to purchase Apollo team plan",
    last_tested_date: null, priority: "Medium" as const,
    created_at: "2026-05-12T00:00:00Z", updated_at: NOW,
    client: { id: "cl6", company_name: "ScaleUp Ventures" },
    project: { id: "pr6", project_name: "ScaleUp Lead Gen Setup" },
    responsible: { id: "demo-profile-5", full_name: "Bilal Siddiqui" },
  },
];

export const DEMO_BLOCKERS = [
  {
    id: "bl1", client_id: "cl1", project_id: "pr1", related_task_id: null, related_access_id: "ac1",
    title: "LinkedIn Sales Navigator access not received",
    description: "Pipeline cannot proceed to LinkedIn export step without team seat access.",
    needed_from: "Client" as const, impact: "High" as const, status: "Open" as const,
    responsible_user_id: "demo-profile-1",
    requested_date: "2026-05-01", follow_up_date: "2026-05-20",
    resolved_at: null, resolution_notes: null,
    notes: "Sent 3 follow-up messages. Tommy says he is working on it.",
    asked_client_at: null, asked_client_message: null,
    created_at: "2026-05-01T00:00:00Z", updated_at: NOW,
    client: { id: "cl1", company_name: "Tongal Media" },
    project: { id: "pr1", project_name: "OpenClaw Lead Pipeline" },
    responsible: { id: "demo-profile-1", full_name: "Nouman Ejaz" },
  },
  {
    id: "bl2", client_id: "cl3", project_id: "pr3", related_task_id: "t3", related_access_id: "ac3",
    title: "SMTP credentials not provided by Dr. Steve",
    description: "Entire email system setup is blocked. Project cannot proceed at all.",
    needed_from: "Client" as const, impact: "Critical" as const, status: "Open" as const,
    responsible_user_id: "demo-profile-2",
    requested_date: "2026-04-15", follow_up_date: "2026-05-18",
    resolved_at: null, resolution_notes: null,
    notes: "Escalate if no response by May 18.",
    asked_client_at: null, asked_client_message: null,
    created_at: "2026-04-15T00:00:00Z", updated_at: NOW,
    client: { id: "cl3", company_name: "MedReach Clinics" },
    project: { id: "pr3", project_name: "MedReach Email System" },
    responsible: { id: "demo-profile-2", full_name: "Zara Khan" },
  },
  {
    id: "bl3", client_id: "cl3", project_id: "pr3", related_task_id: null, related_access_id: null,
    title: "Patient data export format undefined",
    description: "Need sample patient data export or CRM API documentation before building the parser.",
    needed_from: "Client" as const, impact: "High" as const, status: "Open" as const,
    responsible_user_id: "demo-profile-2",
    requested_date: "2026-04-20", follow_up_date: "2026-05-18",
    resolved_at: null, resolution_notes: null, notes: null,
    asked_client_at: null, asked_client_message: null,
    created_at: "2026-04-20T00:00:00Z", updated_at: NOW,
    client: { id: "cl3", company_name: "MedReach Clinics" },
    project: { id: "pr3", project_name: "MedReach Email System" },
    responsible: { id: "demo-profile-2", full_name: "Zara Khan" },
  },
  {
    id: "bl4", client_id: "cl5", project_id: "pr5", related_task_id: "t5", related_access_id: "ac5",
    title: "VPS SSH access for BuildRight not received",
    description: "n8n deployment and go-live blocked. Need root SSH access for Hostinger VPS.",
    needed_from: "Client" as const, impact: "High" as const, status: "Open" as const,
    responsible_user_id: "demo-profile-3",
    requested_date: "2026-05-08", follow_up_date: "2026-05-22",
    resolved_at: null, resolution_notes: null,
    notes: "James keeps saying he will send it. Need to escalate.",
    asked_client_at: null, asked_client_message: null,
    created_at: "2026-05-08T00:00:00Z", updated_at: NOW,
    client: { id: "cl5", company_name: "BuildRight Construction" },
    project: { id: "pr5", project_name: "BuildRight n8n Automation" },
    responsible: { id: "demo-profile-3", full_name: "Omar Farooq" },
  },
];

export const DEMO_DELIVERABLES = [
  {
    id: "d1", client_id: "cl1", project_id: "pr1",
    title: "OpenClaw Pipeline Architecture Doc", description: "Full architecture overview including data flow diagrams",
    deliverable_type: "Documentation", status: "Sent" as const,
    file_url: null, external_url: "https://docs.google.com/openclaw-arch",
    created_by: "demo-profile-1", sent_date: "2026-04-20", approved_date: null,
    client_visible: true, notes: null,
    created_at: "2026-04-18T00:00:00Z", updated_at: NOW,
    client: { id: "cl1", company_name: "Tongal Media" },
    project: { id: "pr1", project_name: "OpenClaw Lead Pipeline" },
    creator: { id: "demo-profile-1", full_name: "Nouman Ejaz" },
  },
  {
    id: "d2", client_id: "cl1", project_id: "pr1",
    title: "Apollo Integration Live", description: "Apollo pipeline live and processing",
    deliverable_type: "Deployed URL", status: "Approved" as const,
    file_url: null, external_url: "https://app.autoplay.ai/tongal-apollo",
    created_by: "demo-profile-1", sent_date: "2026-04-30", approved_date: "2026-05-02",
    client_visible: true, notes: null,
    created_at: "2026-04-28T00:00:00Z", updated_at: NOW,
    client: { id: "cl1", company_name: "Tongal Media" },
    project: { id: "pr1", project_name: "OpenClaw Lead Pipeline" },
    creator: { id: "demo-profile-1", full_name: "Nouman Ejaz" },
  },
  {
    id: "d3", client_id: "cl2", project_id: "pr2",
    title: "Supplier Email Test Report", description: "Test results for 50-supplier email sequence",
    deliverable_type: "Report", status: "Draft" as const,
    file_url: null, external_url: null,
    created_by: "demo-profile-1", sent_date: null, approved_date: null,
    client_visible: false, notes: null,
    created_at: "2026-05-16T00:00:00Z", updated_at: NOW,
    client: { id: "cl2", company_name: "Global Supplier Outreach" },
    project: { id: "pr2", project_name: "Supplier Email Automation" },
    creator: { id: "demo-profile-1", full_name: "Nouman Ejaz" },
  },
  {
    id: "d4", client_id: "cl4", project_id: "pr4",
    title: "Telegram Bot Fleet - All 3 Bots Live", description: "All 3 bots confirmed live by Frank",
    deliverable_type: "Deployed URL", status: "Approved" as const,
    file_url: null, external_url: "https://t.me/frankbot1",
    created_by: "demo-profile-5", sent_date: "2026-05-10", approved_date: "2026-05-12",
    client_visible: true, notes: null,
    created_at: "2026-05-09T00:00:00Z", updated_at: NOW,
    client: { id: "cl4", company_name: "FrankBot Solutions" },
    project: { id: "pr4", project_name: "Telegram Bot Fleet" },
    creator: { id: "demo-profile-5", full_name: "Bilal Siddiqui" },
  },
  {
    id: "d5", client_id: "cl4", project_id: "pr4",
    title: "FrankBot Handover Documentation", description: "In progress - admin panel guide and webhook docs",
    deliverable_type: "Handover Docs", status: "Draft" as const,
    file_url: null, external_url: null,
    created_by: "demo-profile-5", sent_date: null, approved_date: null,
    client_visible: true, notes: null,
    created_at: "2026-05-14T00:00:00Z", updated_at: NOW,
    client: { id: "cl4", company_name: "FrankBot Solutions" },
    project: { id: "pr4", project_name: "Telegram Bot Fleet" },
    creator: { id: "demo-profile-5", full_name: "Bilal Siddiqui" },
  },
  {
    id: "d6", client_id: "cl6", project_id: "pr6",
    title: "ScaleUp Kickoff Summary", description: "ICP definition, project roadmap, tool list",
    deliverable_type: "Documentation", status: "Sent" as const,
    file_url: null, external_url: "https://docs.google.com/scaleup-kickoff",
    created_by: "demo-profile-1", sent_date: "2026-05-16", approved_date: null,
    client_visible: true, notes: null,
    created_at: "2026-05-15T00:00:00Z", updated_at: NOW,
    client: { id: "cl6", company_name: "ScaleUp Ventures" },
    project: { id: "pr6", project_name: "ScaleUp Lead Gen Setup" },
    creator: { id: "demo-profile-1", full_name: "Nouman Ejaz" },
  },
];

export const DEMO_PROFILES = [
  {
    id: "demo-profile-1", auth_user_id: "demo-user-1", full_name: "Nouman Ejaz",
    email: "nouman@autoplay.ai", role: "admin" as const,
    job_title: "Founder & Lead Engineer", department: "Engineering",
    profile_photo_url: null, phone: "+1 514-555-0100", timezone: "EST",
    location: "Montreal, QC", bio: "Founder of Autoplay. Builds AI-powered systems for client automation.",
    skills: ["AI/ML", "Next.js", "Python", "n8n", "Supabase", "OpenAI API"],
    years_experience: 6, certifications: ["AWS Solutions Architect", "Google Cloud Professional"],
    linkedin_url: "https://linkedin.com/in/nouman", portfolio_url: null,
    availability_status: "Busy" as const, is_active: true,
    created_at: "2026-01-01T00:00:00Z", updated_at: NOW,
  },
  {
    id: "demo-profile-2", auth_user_id: "demo-user-2", full_name: "Zara Khan",
    email: "zara@autoplay.ai", role: "user" as const,
    job_title: "AI/ML Engineer", department: "AI",
    profile_photo_url: null, phone: null, timezone: "EST",
    location: "Toronto, ON", bio: "Specializes in voice AI agents, LLM pipelines, and intelligent automation.",
    skills: ["Python", "LangChain", "OpenAI", "Pinecone", "FastAPI"],
    years_experience: 4, certifications: ["DeepLearning.AI"],
    linkedin_url: null, portfolio_url: null,
    availability_status: "Available" as const, is_active: true,
    created_at: "2026-01-01T00:00:00Z", updated_at: NOW,
  },
  {
    id: "demo-profile-3", auth_user_id: "demo-user-3", full_name: "Omar Farooq",
    email: "omar@autoplay.ai", role: "user" as const,
    job_title: "Backend & DevOps Engineer", department: "Engineering",
    profile_photo_url: null, phone: null, timezone: "PKT",
    location: "Lahore, PK", bio: "Handles all backend infrastructure, VPS deployments, and DevOps pipelines.",
    skills: ["Node.js", "Docker", "VPS", "Nginx", "PostgreSQL", "Redis"],
    years_experience: 5, certifications: ["Docker Certified Associate"],
    linkedin_url: null, portfolio_url: null,
    availability_status: "Busy" as const, is_active: true,
    created_at: "2026-01-01T00:00:00Z", updated_at: NOW,
  },
  {
    id: "demo-profile-4", auth_user_id: "demo-user-4", full_name: "Aisha Malik",
    email: "aisha@autoplay.ai", role: "user" as const,
    job_title: "Frontend Engineer", department: "Engineering",
    profile_photo_url: null, phone: null, timezone: "PKT",
    location: "Karachi, PK", bio: "Builds beautiful, responsive frontend interfaces and internal dashboards.",
    skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Figma"],
    years_experience: 3, certifications: ["Meta Frontend Developer"],
    linkedin_url: "https://linkedin.com/in/aishamalik", portfolio_url: null,
    availability_status: "Available" as const, is_active: true,
    created_at: "2026-01-01T00:00:00Z", updated_at: NOW,
  },
  {
    id: "demo-profile-5", auth_user_id: "demo-user-5", full_name: "Bilal Siddiqui",
    email: "bilal@autoplay.ai", role: "user" as const,
    job_title: "Integration Specialist", department: "Automation",
    profile_photo_url: null, phone: null, timezone: "GST",
    location: "Dubai, UAE", bio: "Expert in no-code/low-code automation, webhook integrations, and bot development.",
    skills: ["n8n", "Zapier", "Make.com", "Webhooks", "REST APIs", "Telegram API"],
    years_experience: 4, certifications: ["n8n Certified", "Make.com Expert"],
    linkedin_url: null, portfolio_url: null,
    availability_status: "Busy" as const, is_active: true,
    created_at: "2026-01-01T00:00:00Z", updated_at: NOW,
  },
];
