import type {
  Client,
  Project,
  Task,
  TeamMember,
  TimeLog,
  Asset,
  AccessItem,
  Blocker,
  Deliverable,
  Approval,
  TimelineEntry,
  AISummary,
} from "./types";

// ─── TEAM MEMBERS ────────────────────────────────────────────────────────────

export const teamMembers: TeamMember[] = [
  {
    id: "tm1",
    name: "Nouman Ejaz",
    initials: "NE",
    color: "#6366f1",
    role: "Founder & Lead Engineer",
    department: "Engineering",
    skills: ["AI/ML", "Next.js", "Python", "n8n", "Supabase", "OpenAI API", "System Architecture"],
    bio: "Founder of Autoplay. Builds AI-powered systems for client automation and lead generation.",
    yearsOfExperience: 6,
    activeClients: ["cl1", "cl2", "cl3", "cl4"],
    activeTasks: 12,
    weeklyHoursLogged: 38,
    availabilityStatus: "Busy",
    strengths: ["AI Integration", "Full-stack Architecture", "Client Strategy", "Automation Pipelines"],
    location: "Montreal, QC",
    timezone: "EST",
    certifications: ["AWS Solutions Architect", "Google Cloud Professional"],
    featuredProjects: ["OpenClaw Gateway", "Lead Gen Automation", "AI Voice Agent"],
    email: "nouman@autoplay.ai",
    github: "github.com/nouman",
    linkedin: "linkedin.com/in/nouman",
  },
  {
    id: "tm2",
    name: "Zara Khan",
    initials: "ZK",
    color: "#8b5cf6",
    role: "AI/ML Engineer",
    department: "AI",
    skills: ["Python", "LangChain", "OpenAI", "Pinecone", "FastAPI", "Vapi", "Whisper"],
    bio: "Specializes in voice AI agents, LLM pipelines, and intelligent automation systems.",
    yearsOfExperience: 4,
    activeClients: ["cl3", "cl4", "cl5"],
    activeTasks: 8,
    weeklyHoursLogged: 32,
    availabilityStatus: "Available",
    strengths: ["Voice AI", "LLM Engineering", "RAG Systems", "Prompt Engineering"],
    location: "Toronto, ON",
    timezone: "EST",
    certifications: ["DeepLearning.AI", "Hugging Face NLP"],
    featuredProjects: ["AI Voice Agent", "Telegram Bot Automation"],
    email: "zara@autoplay.ai",
    github: "github.com/zarakhan",
  },
  {
    id: "tm3",
    name: "Omar Farooq",
    initials: "OF",
    color: "#06b6d4",
    role: "Backend & DevOps Engineer",
    department: "Engineering",
    skills: ["Node.js", "Docker", "VPS", "Nginx", "PostgreSQL", "Redis", "Tailscale", "CI/CD"],
    bio: "Handles all backend infrastructure, VPS deployments, and DevOps pipelines.",
    yearsOfExperience: 5,
    activeClients: ["cl1", "cl5", "cl6"],
    activeTasks: 10,
    weeklyHoursLogged: 36,
    availabilityStatus: "Busy",
    strengths: ["Infrastructure", "Deployment Automation", "Database Optimization", "Security"],
    location: "Lahore, PK",
    timezone: "PKT",
    certifications: ["Docker Certified Associate", "Linux Foundation LFCS"],
    featuredProjects: ["VPS Automation Suite", "n8n Deployment"],
    email: "omar@autoplay.ai",
    github: "github.com/omarfarooq",
  },
  {
    id: "tm4",
    name: "Aisha Malik",
    initials: "AM",
    color: "#10b981",
    role: "Frontend Engineer",
    department: "Engineering",
    skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Framer Motion", "Figma"],
    bio: "Builds beautiful, responsive frontend interfaces and internal dashboards.",
    yearsOfExperience: 3,
    activeClients: ["cl2", "cl4"],
    activeTasks: 6,
    weeklyHoursLogged: 28,
    availabilityStatus: "Available",
    strengths: ["UI/UX Design", "Component Architecture", "Animation", "Design Systems"],
    location: "Karachi, PK",
    timezone: "PKT",
    certifications: ["Meta Frontend Developer", "Google UX Design"],
    featuredProjects: ["Client Dashboard", "Autoplay Internal System"],
    email: "aisha@autoplay.ai",
    linkedin: "linkedin.com/in/aishamalik",
  },
  {
    id: "tm5",
    name: "Bilal Siddiqui",
    initials: "BS",
    color: "#f59e0b",
    role: "Integration Specialist",
    department: "Automation",
    skills: ["n8n", "Zapier", "Make.com", "Webhooks", "REST APIs", "Telegram API", "WhatsApp API"],
    bio: "Expert in no-code/low-code automation, webhook integrations, and bot development.",
    yearsOfExperience: 4,
    activeClients: ["cl4", "cl5", "cl6"],
    activeTasks: 9,
    weeklyHoursLogged: 30,
    availabilityStatus: "Busy",
    strengths: ["n8n Workflows", "Bot Development", "API Integrations", "Process Automation"],
    location: "Dubai, UAE",
    timezone: "GST",
    certifications: ["n8n Certified", "Make.com Expert"],
    featuredProjects: ["Telegram Bot Fleet", "n8n Automation Suite"],
    email: "bilal@autoplay.ai",
  },
];

// ─── CLIENTS ─────────────────────────────────────────────────────────────────

export const clients: Client[] = [
  {
    id: "cl1",
    name: "Tommy",
    company: "Tongal Media",
    initials: "TM",
    color: "#6366f1",
    contactPerson: "Tommy Chen",
    contactEmail: "tommy@tongal.com",
    contactPhone: "+1 310-555-0142",
    preferredChannel: "WhatsApp",
    timezone: "PST",
    projectType: "Lead Generation & CRM Automation",
    assignedOwner: "Nouman Ejaz",
    assignedTeam: ["tm1", "tm5"],
    status: "Active",
    healthScore: "Good",
    priority: "High",
    lastActivity: "2026-05-16",
    openBlockers: 1,
    totalHoursSpent: 84,
    projectStage: "Development",
    progress: 68,
    latestUpdate:
      "OpenClaw gateway verified. Apollo CSV pipeline tested. Awaiting LinkedIn Sales Navigator access.",
    completedItems: ["OpenClaw gateway setup", "Apollo integration", "Initial data pipeline"],
    pendingItems: ["LinkedIn export integration", "Final CSV automation", "Client review session"],
    blockingItems: ["LinkedIn Sales Navigator credentials pending"],
    neededFromClient: ["LinkedIn Sales Navigator login", "Preferred export schedule"],
    pinnedLinks: [
      { title: "Tongal Google Sheet", url: "https://sheets.google.com", type: "Google Sheet" },
      { title: "Project Brief", url: "https://docs.google.com", type: "Google Doc" },
    ],
    contractStart: "2026-03-01",
    contractEnd: "2026-06-30",
    revenue: 8500,
    notes: "High priority client. Very responsive on WhatsApp.",
  },
  {
    id: "cl2",
    name: "Robert",
    company: "Global Supplier Outreach",
    initials: "GS",
    color: "#8b5cf6",
    contactPerson: "Robert Williams",
    contactEmail: "robert@globalsupplier.co",
    preferredChannel: "Email",
    timezone: "EST",
    projectType: "Supplier Outreach Automation",
    assignedOwner: "Nouman Ejaz",
    assignedTeam: ["tm1", "tm4"],
    status: "Active",
    healthScore: "Healthy",
    priority: "High",
    lastActivity: "2026-05-15",
    openBlockers: 0,
    totalHoursSpent: 62,
    projectStage: "Testing",
    progress: 82,
    latestUpdate:
      "Email automation pipeline complete. 500 suppliers contacted. Testing phase underway.",
    completedItems: ["Email sequences built", "Supplier list cleaned", "SMTP configured", "Tracking implemented"],
    pendingItems: ["Final round testing", "Response handling automation", "Handover documentation"],
    blockingItems: [],
    neededFromClient: ["Approval on email copy", "Final supplier list update"],
    pinnedLinks: [
      { title: "Supplier Database", url: "https://sheets.google.com", type: "Google Sheet" },
    ],
    contractStart: "2026-02-15",
    contractEnd: "2026-05-31",
    revenue: 6200,
  },
  {
    id: "cl3",
    name: "Dr. Steve",
    company: "MedReach Clinics",
    initials: "MS",
    color: "#10b981",
    contactPerson: "Dr. Steve Hartman",
    contactEmail: "steve@medreach.clinic",
    contactPhone: "+1 905-555-0198",
    preferredChannel: "Zoom",
    timezone: "EST",
    projectType: "Email System & Patient Automation",
    assignedOwner: "Zara Khan",
    assignedTeam: ["tm2", "tm1"],
    status: "At Risk",
    healthScore: "At Risk",
    priority: "Critical",
    lastActivity: "2026-05-14",
    openBlockers: 2,
    totalHoursSpent: 45,
    projectStage: "Access Collection",
    progress: 35,
    latestUpdate:
      "SMTP access still pending. Cannot proceed with email system setup until credentials received.",
    completedItems: ["Requirements documented", "Email templates drafted", "Workflow mapped"],
    pendingItems: ["SMTP setup", "Patient data integration", "Compliance review"],
    blockingItems: ["SMTP credentials not received", "Patient data format unclear"],
    neededFromClient: ["SMTP credentials", "Patient CRM export format", "Compliance sign-off"],
    pinnedLinks: [
      { title: "Requirements Doc", url: "https://docs.google.com", type: "Google Doc" },
    ],
    contractStart: "2026-04-01",
    revenue: 4800,
    notes: "Slow to respond. Follow up via phone if email ignored.",
  },
  {
    id: "cl4",
    name: "Frank",
    company: "FrankBot Solutions",
    initials: "FB",
    color: "#06b6d4",
    contactPerson: "Frank Okonkwo",
    contactEmail: "frank@frankbot.io",
    preferredChannel: "Telegram",
    timezone: "WAT",
    projectType: "Telegram Bot Agents",
    assignedOwner: "Bilal Siddiqui",
    assignedTeam: ["tm5", "tm2", "tm4"],
    status: "Active",
    healthScore: "Healthy",
    priority: "Medium",
    lastActivity: "2026-05-17",
    openBlockers: 0,
    totalHoursSpent: 91,
    projectStage: "Deployment",
    progress: 91,
    latestUpdate:
      "All 3 Telegram bots deployed and live. Webhook delivery confirmed. Minor UI polish remaining.",
    completedItems: [
      "Bot 1 deployed",
      "Bot 2 deployed",
      "Bot 3 deployed",
      "Webhook pipeline tested",
      "Admin panel built",
    ],
    pendingItems: ["UI polish on admin panel", "Client handover docs"],
    blockingItems: [],
    neededFromClient: ["Final approval on bot behavior", "Production Telegram token"],
    pinnedLinks: [
      { title: "Bot Dashboard", url: "https://t.me/frankbot_admin", type: "Other" },
    ],
    contractStart: "2026-01-10",
    contractEnd: "2026-05-30",
    revenue: 12000,
  },
  {
    id: "cl5",
    name: "Construction Co.",
    company: "BuildRight Construction",
    initials: "BR",
    color: "#f59e0b",
    contactPerson: "James Patterson",
    contactEmail: "james@buildright.com",
    preferredChannel: "WhatsApp",
    timezone: "MST",
    projectType: "n8n Workflow Automation",
    assignedOwner: "Bilal Siddiqui",
    assignedTeam: ["tm5", "tm3"],
    status: "Active",
    healthScore: "Good",
    priority: "Medium",
    lastActivity: "2026-05-13",
    openBlockers: 1,
    totalHoursSpent: 53,
    projectStage: "Development",
    progress: 55,
    latestUpdate:
      "Core n8n workflows built. Awaiting VPS access to deploy. Form submission automation 80% complete.",
    completedItems: ["Workflow diagrams approved", "n8n local setup", "Form automation built"],
    pendingItems: ["VPS deployment", "Live testing", "Training session"],
    blockingItems: ["VPS credentials pending from client"],
    neededFromClient: ["VPS SSH access", "Domain DNS credentials"],
    pinnedLinks: [],
    contractStart: "2026-03-20",
    revenue: 5500,
  },
  {
    id: "cl6",
    name: "Dean",
    company: "ScaleUp Ventures",
    initials: "SV",
    color: "#ec4899",
    contactPerson: "Dean Martinez",
    contactEmail: "dean@scaleup.vc",
    contactPhone: "+1 512-555-0177",
    preferredChannel: "Slack",
    timezone: "CST",
    projectType: "Lead Generation Setup",
    assignedOwner: "Nouman Ejaz",
    assignedTeam: ["tm1", "tm5", "tm3"],
    status: "Onboarding",
    healthScore: "Healthy",
    priority: "High",
    lastActivity: "2026-05-17",
    openBlockers: 0,
    totalHoursSpent: 18,
    projectStage: "Discovery",
    progress: 15,
    latestUpdate:
      "Kickoff call completed. Requirements gathered. Setting up Apollo and ZoomInfo accounts.",
    completedItems: ["Kickoff call", "Requirements doc", "ICP definition"],
    pendingItems: [
      "Apollo account setup",
      "ZoomInfo access",
      "Lead scoring model",
      "Outreach sequences",
    ],
    blockingItems: [],
    neededFromClient: ["Apollo login details", "ZoomInfo license confirmation", "Budget approval"],
    pinnedLinks: [
      { title: "Kickoff Notes", url: "https://docs.google.com", type: "Google Doc" },
    ],
    contractStart: "2026-05-10",
    revenue: 9000,
  },
];

// ─── PROJECTS ─────────────────────────────────────────────────────────────────

export const projects: Project[] = [
  {
    id: "pr1",
    name: "OpenClaw Lead Pipeline",
    clientId: "cl1",
    clientName: "Tommy / Tongal",
    description: "Automated lead extraction and ingestion via OpenClaw gateway with Apollo enrichment",
    projectType: "Lead Generation",
    startDate: "2026-03-01",
    dueDate: "2026-06-15",
    currentPhase: "Development",
    status: "Active",
    progress: 68,
    assignedTeam: ["Nouman Ejaz", "Bilal Siddiqui"],
    milestones: [
      { id: "m1", title: "OpenClaw Gateway Setup", dueDate: "2026-03-20", completed: true },
      { id: "m2", title: "Apollo Integration", dueDate: "2026-04-10", completed: true },
      { id: "m3", title: "LinkedIn Export Integration", dueDate: "2026-05-30", completed: false },
      { id: "m4", title: "Final Automation & Handover", dueDate: "2026-06-15", completed: false },
    ],
    timeSpent: 84,
    estimatedHours: 120,
    tags: ["lead-gen", "openclaw", "apollo", "automation"],
  },
  {
    id: "pr2",
    name: "Supplier Email Automation",
    clientId: "cl2",
    clientName: "Robert / Global Supplier",
    description: "Automated email outreach to 5000+ suppliers with response tracking and CRM sync",
    projectType: "Email Automation",
    startDate: "2026-02-15",
    dueDate: "2026-05-31",
    currentPhase: "Testing",
    status: "Active",
    progress: 82,
    assignedTeam: ["Nouman Ejaz", "Aisha Malik"],
    milestones: [
      { id: "m5", title: "SMTP Configuration", dueDate: "2026-03-01", completed: true },
      { id: "m6", title: "Email Sequence Build", dueDate: "2026-03-30", completed: true },
      { id: "m7", title: "Supplier DB Cleanup", dueDate: "2026-04-15", completed: true },
      { id: "m8", title: "Testing & Go-Live", dueDate: "2026-05-31", completed: false },
    ],
    timeSpent: 62,
    estimatedHours: 80,
    tags: ["email", "smtp", "outreach", "automation"],
  },
  {
    id: "pr3",
    name: "MedReach Email System",
    clientId: "cl3",
    clientName: "Dr. Steve / MedReach",
    description: "Patient communication email system with appointment reminders and follow-ups",
    projectType: "Email System",
    startDate: "2026-04-01",
    dueDate: "2026-06-30",
    currentPhase: "Access Collection",
    status: "On Hold",
    progress: 35,
    assignedTeam: ["Zara Khan", "Nouman Ejaz"],
    milestones: [
      { id: "m9", title: "Requirements & Design", dueDate: "2026-04-20", completed: true },
      { id: "m10", title: "SMTP Setup", dueDate: "2026-05-10", completed: false },
      { id: "m11", title: "Template Build", dueDate: "2026-05-31", completed: false },
      { id: "m12", title: "Testing & Compliance", dueDate: "2026-06-20", completed: false },
    ],
    timeSpent: 45,
    estimatedHours: 100,
    tags: ["email", "healthcare", "automation"],
  },
  {
    id: "pr4",
    name: "Telegram Bot Fleet",
    clientId: "cl4",
    clientName: "Frank / FrankBot",
    description: "3 Telegram bots with AI responses, admin panel, and webhook delivery pipeline",
    projectType: "Bot Development",
    startDate: "2026-01-10",
    dueDate: "2026-05-30",
    currentPhase: "Deployment",
    status: "Active",
    progress: 91,
    assignedTeam: ["Bilal Siddiqui", "Zara Khan", "Aisha Malik"],
    milestones: [
      { id: "m13", title: "Bot Architecture Design", dueDate: "2026-01-30", completed: true },
      { id: "m14", title: "Bot 1 Deployment", dueDate: "2026-03-01", completed: true },
      { id: "m15", title: "Bot 2 & 3 Deployment", dueDate: "2026-04-15", completed: true },
      { id: "m16", title: "Admin Panel & Handover", dueDate: "2026-05-30", completed: false },
    ],
    timeSpent: 91,
    estimatedHours: 100,
    tags: ["telegram", "bots", "ai", "webhook"],
  },
  {
    id: "pr5",
    name: "BuildRight n8n Automation",
    clientId: "cl5",
    clientName: "Construction Co. / BuildRight",
    description: "n8n workflow automation for construction project management and form submissions",
    projectType: "Workflow Automation",
    startDate: "2026-03-20",
    dueDate: "2026-06-20",
    currentPhase: "Development",
    status: "Active",
    progress: 55,
    assignedTeam: ["Bilal Siddiqui", "Omar Farooq"],
    milestones: [
      { id: "m17", title: "Workflow Design", dueDate: "2026-04-01", completed: true },
      { id: "m18", title: "n8n Build", dueDate: "2026-05-01", completed: true },
      { id: "m19", title: "VPS Deployment", dueDate: "2026-06-01", completed: false },
      { id: "m20", title: "Training & Handover", dueDate: "2026-06-20", completed: false },
    ],
    timeSpent: 53,
    estimatedHours: 90,
    tags: ["n8n", "automation", "construction", "vps"],
  },
  {
    id: "pr6",
    name: "ScaleUp Lead Gen Setup",
    clientId: "cl6",
    clientName: "Dean / ScaleUp",
    description: "Full lead generation infrastructure with Apollo, ZoomInfo, and outreach automation",
    projectType: "Lead Generation",
    startDate: "2026-05-10",
    dueDate: "2026-07-31",
    currentPhase: "Discovery",
    status: "Planning",
    progress: 15,
    assignedTeam: ["Nouman Ejaz", "Bilal Siddiqui", "Omar Farooq"],
    milestones: [
      { id: "m21", title: "Discovery & ICP Definition", dueDate: "2026-05-20", completed: true },
      { id: "m22", title: "Tool Setup", dueDate: "2026-06-05", completed: false },
      { id: "m23", title: "Sequence Build", dueDate: "2026-06-30", completed: false },
      { id: "m24", title: "Go Live", dueDate: "2026-07-31", completed: false },
    ],
    timeSpent: 18,
    estimatedHours: 120,
    tags: ["lead-gen", "apollo", "zoominfo", "outreach"],
  },
];

// ─── TASKS ───────────────────────────────────────────────────────────────────

export const tasks: Task[] = [
  {
    id: "t1",
    title: "Integrate LinkedIn Sales Navigator export to OpenClaw pipeline",
    description: "Once LinkedIn access received, build the export → parse → ingest pipeline",
    clientId: "cl1",
    clientName: "Tommy / Tongal",
    projectId: "pr1",
    projectName: "OpenClaw Lead Pipeline",
    assignedPerson: "Nouman Ejaz",
    priority: "High",
    status: "Waiting on Client",
    dueDate: "2026-05-30",
    estimatedHours: 8,
    loggedHours: 0,
    tags: ["linkedin", "openclaw", "integration"],
    isInternal: true,
    isClientVisible: false,
    createdAt: "2026-05-10",
    updatedAt: "2026-05-15",
  },
  {
    id: "t2",
    title: "Final testing of supplier email sequences",
    description: "Run full end-to-end test with 50 test suppliers before go-live",
    clientId: "cl2",
    clientName: "Robert / Supplier Outreach",
    projectId: "pr2",
    projectName: "Supplier Email Automation",
    assignedPerson: "Nouman Ejaz",
    priority: "High",
    status: "In Progress",
    dueDate: "2026-05-25",
    estimatedHours: 6,
    loggedHours: 2,
    tags: ["testing", "email", "qa"],
    isInternal: true,
    isClientVisible: false,
    createdAt: "2026-05-12",
    updatedAt: "2026-05-16",
  },
  {
    id: "t3",
    title: "SMTP setup for MedReach",
    description: "Configure SMTP with Dr. Steve's credentials once received",
    clientId: "cl3",
    clientName: "Dr. Steve / MedReach",
    projectId: "pr3",
    projectName: "MedReach Email System",
    assignedPerson: "Zara Khan",
    priority: "Critical",
    status: "Blocked",
    dueDate: "2026-05-20",
    estimatedHours: 4,
    loggedHours: 0,
    tags: ["smtp", "blocked", "access"],
    isInternal: true,
    isClientVisible: false,
    createdAt: "2026-05-01",
    updatedAt: "2026-05-14",
  },
  {
    id: "t4",
    title: "Deploy Telegram admin panel to production",
    description: "Final production deployment of the FrankBot admin interface",
    clientId: "cl4",
    clientName: "Frank / FrankBot",
    projectId: "pr4",
    projectName: "Telegram Bot Fleet",
    assignedPerson: "Aisha Malik",
    priority: "Medium",
    status: "In Progress",
    dueDate: "2026-05-28",
    estimatedHours: 5,
    loggedHours: 3,
    tags: ["deployment", "admin", "frontend"],
    isInternal: true,
    isClientVisible: true,
    createdAt: "2026-05-13",
    updatedAt: "2026-05-17",
  },
  {
    id: "t5",
    title: "Deploy n8n to BuildRight VPS",
    description: "SSH into VPS, install n8n, configure domain and SSL",
    clientId: "cl5",
    clientName: "Construction Co.",
    projectId: "pr5",
    projectName: "BuildRight n8n Automation",
    assignedPerson: "Omar Farooq",
    priority: "High",
    status: "Waiting on Client",
    dueDate: "2026-06-01",
    estimatedHours: 6,
    loggedHours: 0,
    tags: ["vps", "n8n", "deployment"],
    isInternal: true,
    isClientVisible: false,
    createdAt: "2026-05-10",
    updatedAt: "2026-05-14",
  },
  {
    id: "t6",
    title: "Set up Apollo account for ScaleUp",
    description: "Configure Apollo.io with ICP filters and export sequences",
    clientId: "cl6",
    clientName: "Dean / ScaleUp",
    projectId: "pr6",
    projectName: "ScaleUp Lead Gen Setup",
    assignedPerson: "Bilal Siddiqui",
    priority: "Medium",
    status: "To Do",
    dueDate: "2026-06-05",
    estimatedHours: 4,
    loggedHours: 0,
    tags: ["apollo", "lead-gen", "setup"],
    isInternal: true,
    isClientVisible: true,
    createdAt: "2026-05-15",
    updatedAt: "2026-05-15",
  },
  {
    id: "t7",
    title: "Write handover documentation for Telegram bots",
    description: "Create full handover doc including bot commands, admin panel guide, and webhook docs",
    clientId: "cl4",
    clientName: "Frank / FrankBot",
    projectId: "pr4",
    projectName: "Telegram Bot Fleet",
    assignedPerson: "Bilal Siddiqui",
    priority: "Low",
    status: "To Do",
    dueDate: "2026-05-30",
    estimatedHours: 3,
    loggedHours: 0,
    tags: ["documentation", "handover"],
    isInternal: false,
    isClientVisible: true,
    createdAt: "2026-05-14",
    updatedAt: "2026-05-14",
  },
  {
    id: "t8",
    title: "Autoplay internal dashboard build",
    description: "Build the Autoplay internal ClientOps platform",
    clientId: "cl1",
    clientName: "Internal",
    projectId: "pr1",
    projectName: "Internal Tooling",
    assignedPerson: "Aisha Malik",
    priority: "High",
    status: "In Progress",
    dueDate: "2026-05-31",
    estimatedHours: 40,
    loggedHours: 22,
    tags: ["internal", "dashboard", "next.js"],
    isInternal: true,
    isClientVisible: false,
    createdAt: "2026-05-01",
    updatedAt: "2026-05-17",
  },
  {
    id: "t9",
    title: "ZoomInfo account configuration for ScaleUp",
    clientId: "cl6",
    clientName: "Dean / ScaleUp",
    projectId: "pr6",
    projectName: "ScaleUp Lead Gen Setup",
    assignedPerson: "Nouman Ejaz",
    priority: "Medium",
    status: "Backlog",
    dueDate: "2026-06-10",
    estimatedHours: 3,
    loggedHours: 0,
    tags: ["zoominfo", "lead-gen"],
    isInternal: true,
    isClientVisible: false,
    createdAt: "2026-05-16",
    updatedAt: "2026-05-16",
  },
  {
    id: "t10",
    title: "Patient data integration planning for MedReach",
    clientId: "cl3",
    clientName: "Dr. Steve / MedReach",
    projectId: "pr3",
    projectName: "MedReach Email System",
    assignedPerson: "Zara Khan",
    priority: "High",
    status: "Waiting on Client",
    dueDate: "2026-05-25",
    estimatedHours: 8,
    loggedHours: 2,
    tags: ["healthcare", "data", "integration"],
    isInternal: true,
    isClientVisible: false,
    createdAt: "2026-05-08",
    updatedAt: "2026-05-14",
  },
  {
    id: "t11",
    title: "Write weekly update for Robert",
    clientId: "cl2",
    clientName: "Robert / Supplier Outreach",
    projectId: "pr2",
    projectName: "Supplier Email Automation",
    assignedPerson: "Nouman Ejaz",
    priority: "Low",
    status: "Completed",
    dueDate: "2026-05-15",
    estimatedHours: 1,
    loggedHours: 1,
    tags: ["communication", "update"],
    isInternal: false,
    isClientVisible: true,
    createdAt: "2026-05-14",
    updatedAt: "2026-05-15",
  },
  {
    id: "t12",
    title: "Test webhook delivery for all 3 FrankBots",
    clientId: "cl4",
    clientName: "Frank / FrankBot",
    projectId: "pr4",
    projectName: "Telegram Bot Fleet",
    assignedPerson: "Bilal Siddiqui",
    priority: "High",
    status: "Completed",
    dueDate: "2026-05-10",
    estimatedHours: 4,
    loggedHours: 4,
    tags: ["testing", "webhook", "telegram"],
    isInternal: true,
    isClientVisible: false,
    createdAt: "2026-05-05",
    updatedAt: "2026-05-10",
  },
];

// ─── TIME LOGS ───────────────────────────────────────────────────────────────

export const timeLogs: TimeLog[] = [
  {
    id: "tl1",
    teamMemberId: "tm1",
    teamMemberName: "Nouman Ejaz",
    clientId: "cl1",
    clientName: "Tommy / Tongal",
    projectId: "pr1",
    projectName: "OpenClaw Lead Pipeline",
    taskId: "t1",
    taskName: "LinkedIn integration planning",
    date: "2026-05-16",
    hours: 3,
    description: "Pipeline architecture review and LinkedIn API docs research",
    billable: true,
    approved: true,
    category: "Research",
  },
  {
    id: "tl2",
    teamMemberId: "tm1",
    teamMemberName: "Nouman Ejaz",
    clientId: "cl2",
    clientName: "Robert / Supplier Outreach",
    projectId: "pr2",
    projectName: "Supplier Email Automation",
    taskId: "t2",
    taskName: "Email sequence testing",
    date: "2026-05-16",
    hours: 2,
    description: "End-to-end test run with 50 test emails",
    billable: true,
    approved: true,
    category: "Testing",
  },
  {
    id: "tl3",
    teamMemberId: "tm2",
    teamMemberName: "Zara Khan",
    clientId: "cl3",
    clientName: "Dr. Steve / MedReach",
    projectId: "pr3",
    projectName: "MedReach Email System",
    date: "2026-05-16",
    hours: 2,
    description: "Follow-up with Dr. Steve on SMTP credentials. Drafted requirements doc update.",
    billable: true,
    approved: false,
    category: "Communication",
  },
  {
    id: "tl4",
    teamMemberId: "tm4",
    teamMemberName: "Aisha Malik",
    clientId: "cl4",
    clientName: "Frank / FrankBot",
    projectId: "pr4",
    projectName: "Telegram Bot Fleet",
    taskId: "t4",
    taskName: "Admin panel deployment",
    date: "2026-05-17",
    hours: 3,
    description: "Production build and deployment of admin panel",
    billable: true,
    approved: false,
    category: "Deployment",
  },
  {
    id: "tl5",
    teamMemberId: "tm5",
    teamMemberName: "Bilal Siddiqui",
    clientId: "cl5",
    clientName: "Construction Co.",
    projectId: "pr5",
    projectName: "BuildRight n8n Automation",
    date: "2026-05-15",
    hours: 4,
    description: "n8n form submission workflow build and testing in local environment",
    billable: true,
    approved: true,
    category: "Development",
  },
  {
    id: "tl6",
    teamMemberId: "tm3",
    teamMemberName: "Omar Farooq",
    clientId: "cl6",
    clientName: "Dean / ScaleUp",
    projectId: "pr6",
    projectName: "ScaleUp Lead Gen Setup",
    date: "2026-05-17",
    hours: 2,
    description: "Infrastructure planning for ScaleUp lead gen stack",
    billable: true,
    approved: false,
    category: "Planning",
  },
  {
    id: "tl7",
    teamMemberId: "tm1",
    teamMemberName: "Nouman Ejaz",
    clientId: "cl6",
    clientName: "Dean / ScaleUp",
    projectId: "pr6",
    projectName: "ScaleUp Lead Gen Setup",
    date: "2026-05-15",
    hours: 3,
    description: "Kickoff call with Dean, ICP documentation, project scoping",
    billable: true,
    approved: true,
    category: "Meeting",
  },
  {
    id: "tl8",
    teamMemberId: "tm5",
    teamMemberName: "Bilal Siddiqui",
    clientId: "cl4",
    clientName: "Frank / FrankBot",
    projectId: "pr4",
    projectName: "Telegram Bot Fleet",
    taskId: "t12",
    taskName: "Webhook testing",
    date: "2026-05-14",
    hours: 4,
    description: "Full webhook delivery test for all 3 bots",
    billable: true,
    approved: true,
    category: "Testing",
  },
];

// ─── ASSETS ──────────────────────────────────────────────────────────────────

export const assets: Asset[] = [
  {
    id: "a1",
    title: "Tongal Lead Database",
    type: "Google Sheet",
    url: "https://sheets.google.com/tongal-leads",
    providedBy: "Tommy Chen",
    dateAdded: "2026-03-05",
    tags: ["leads", "database", "tongal"],
    visibility: "Internal",
    notes: "Contains 10,000 leads. Do not share externally.",
    clientId: "cl1",
    clientName: "Tommy / Tongal",
    projectId: "pr1",
    isPinned: true,
  },
  {
    id: "a2",
    title: "Project Brief - OpenClaw",
    type: "Google Doc",
    url: "https://docs.google.com/openclaw-brief",
    providedBy: "Tommy Chen",
    dateAdded: "2026-03-01",
    tags: ["brief", "requirements"],
    visibility: "Internal",
    clientId: "cl1",
    clientName: "Tommy / Tongal",
    projectId: "pr1",
    isPinned: false,
  },
  {
    id: "a3",
    title: "Supplier Master List",
    type: "Google Sheet",
    url: "https://sheets.google.com/supplier-list",
    providedBy: "Robert Williams",
    dateAdded: "2026-02-20",
    tags: ["suppliers", "outreach"],
    visibility: "Internal",
    notes: "5,280 suppliers. Cleaned and deduped as of March 2026.",
    clientId: "cl2",
    clientName: "Robert / Supplier Outreach",
    projectId: "pr2",
    isPinned: true,
  },
  {
    id: "a4",
    title: "MedReach Requirements Loom",
    type: "Loom",
    url: "https://loom.com/medreach-requirements",
    providedBy: "Dr. Steve Hartman",
    dateAdded: "2026-04-05",
    tags: ["requirements", "video", "healthcare"],
    visibility: "Internal",
    notes: "45 minute walkthrough of patient communication requirements",
    clientId: "cl3",
    clientName: "Dr. Steve / MedReach",
    projectId: "pr3",
    isPinned: false,
  },
  {
    id: "a5",
    title: "FrankBot Brand Assets",
    type: "Brand Assets",
    url: "https://drive.google.com/frankbot-brand",
    providedBy: "Frank Okonkwo",
    dateAdded: "2026-01-15",
    tags: ["branding", "logo", "assets"],
    visibility: "Client-visible",
    clientId: "cl4",
    clientName: "Frank / FrankBot",
    projectId: "pr4",
    isPinned: true,
  },
  {
    id: "a6",
    title: "BuildRight Contract & Scope",
    type: "Contract",
    url: "https://drive.google.com/buildright-contract",
    providedBy: "James Patterson",
    dateAdded: "2026-03-20",
    tags: ["contract", "scope", "legal"],
    visibility: "Internal",
    clientId: "cl5",
    clientName: "Construction Co.",
    projectId: "pr5",
    isPinned: false,
  },
  {
    id: "a7",
    title: "ScaleUp ICP Definition Doc",
    type: "Google Doc",
    url: "https://docs.google.com/scaleup-icp",
    providedBy: "Dean Martinez",
    dateAdded: "2026-05-15",
    tags: ["icp", "lead-gen", "strategy"],
    visibility: "Internal",
    clientId: "cl6",
    clientName: "Dean / ScaleUp",
    projectId: "pr6",
    isPinned: true,
  },
];

// ─── ACCESS ITEMS ─────────────────────────────────────────────────────────────

export const accessItems: AccessItem[] = [
  {
    id: "ac1",
    serviceName: "LinkedIn Sales Navigator",
    category: "Lead Generation",
    status: "Need Client Action",
    owner: "Nouman Ejaz",
    notes: "Waiting for Tommy to share team seat access",
    clientId: "cl1",
    clientName: "Tommy / Tongal",
    projectId: "pr1",
    secureLocation: "Waiting - not yet received",
    actionRequired: "Client to share LinkedIn team account access",
    priority: "High",
  },
  {
    id: "ac2",
    serviceName: "Apollo.io",
    category: "Lead Generation",
    status: "Configured",
    owner: "Nouman Ejaz",
    lastTested: "2026-05-10",
    notes: "Team account configured. ICP filters set.",
    clientId: "cl1",
    clientName: "Tommy / Tongal",
    projectId: "pr1",
    secureLocation: "1Password - Tongal vault",
    priority: "High",
  },
  {
    id: "ac3",
    serviceName: "SMTP / Email Server",
    category: "Email",
    status: "Pending",
    owner: "Zara Khan",
    notes: "Dr. Steve has not provided SMTP credentials yet",
    clientId: "cl3",
    clientName: "Dr. Steve / MedReach",
    projectId: "pr3",
    secureLocation: "Not received - waiting on client",
    actionRequired: "Follow up with Dr. Steve directly via phone",
    priority: "Critical",
  },
  {
    id: "ac4",
    serviceName: "Telegram Bot Token",
    category: "Messaging",
    status: "Received",
    owner: "Bilal Siddiqui",
    lastTested: "2026-05-14",
    notes: "Production token received. Bot is live.",
    clientId: "cl4",
    clientName: "Frank / FrankBot",
    projectId: "pr4",
    secureLocation: "1Password - FrankBot vault",
    priority: "High",
  },
  {
    id: "ac5",
    serviceName: "VPS / Hostinger SSH",
    category: "Infrastructure",
    status: "Need Client Action",
    owner: "Omar Farooq",
    notes: "James needs to provide SSH key or root credentials for BuildRight VPS",
    clientId: "cl5",
    clientName: "Construction Co.",
    projectId: "pr5",
    secureLocation: "Waiting - not yet received",
    actionRequired: "Client to provide VPS SSH access credentials",
    priority: "High",
  },
  {
    id: "ac6",
    serviceName: "Apollo.io",
    category: "Lead Generation",
    status: "Pending",
    owner: "Bilal Siddiqui",
    notes: "Waiting for Dean to purchase Apollo license and share access",
    clientId: "cl6",
    clientName: "Dean / ScaleUp",
    projectId: "pr6",
    secureLocation: "Not received",
    actionRequired: "Dean to purchase Apollo team plan",
    priority: "Medium",
  },
  {
    id: "ac7",
    serviceName: "GitHub Repository",
    category: "Development",
    status: "Configured",
    owner: "Nouman Ejaz",
    lastTested: "2026-05-16",
    notes: "Private repo created. All team members added.",
    clientId: "cl2",
    clientName: "Robert / Supplier Outreach",
    projectId: "pr2",
    secureLocation: "GitHub org - autoplay-internal",
    priority: "Medium",
  },
  {
    id: "ac8",
    serviceName: "Supabase",
    category: "Database",
    status: "Tested",
    owner: "Omar Farooq",
    lastTested: "2026-05-15",
    notes: "Project set up. Tables configured. RLS enabled.",
    clientId: "cl1",
    clientName: "Tommy / Tongal",
    projectId: "pr1",
    secureLocation: "1Password - Tongal vault",
    priority: "High",
  },
];

// ─── BLOCKERS ─────────────────────────────────────────────────────────────────

export const blockers: Blocker[] = [
  {
    id: "bl1",
    title: "LinkedIn Sales Navigator access not received",
    clientId: "cl1",
    clientName: "Tommy / Tongal",
    projectId: "pr1",
    projectName: "OpenClaw Lead Pipeline",
    whatIsBlocked: "LinkedIn lead export → ingestion pipeline",
    whatWeNeed: "LinkedIn Sales Navigator team seat or login credentials",
    neededFrom: "Client",
    requestedDate: "2026-05-01",
    followUpDate: "2026-05-20",
    status: "Open",
    impact: "High",
    owner: "Nouman Ejaz",
    notes: "Sent 3 follow-up messages. Tommy says he is working on it.",
    relatedAccessId: "ac1",
  },
  {
    id: "bl2",
    title: "SMTP credentials not provided by Dr. Steve",
    clientId: "cl3",
    clientName: "Dr. Steve / MedReach",
    projectId: "pr3",
    projectName: "MedReach Email System",
    whatIsBlocked: "Entire email system setup",
    whatWeNeed: "SMTP host, port, username, password",
    neededFrom: "Client",
    requestedDate: "2026-04-15",
    followUpDate: "2026-05-18",
    status: "Open",
    impact: "Critical",
    owner: "Zara Khan",
    notes: "Project cannot proceed at all without this. Escalate if no response by May 18.",
    relatedAccessId: "ac3",
  },
  {
    id: "bl3",
    title: "Patient data export format undefined",
    clientId: "cl3",
    clientName: "Dr. Steve / MedReach",
    projectId: "pr3",
    projectName: "MedReach Email System",
    whatIsBlocked: "Patient data integration design",
    whatWeNeed: "Sample patient data export or CRM API documentation",
    neededFrom: "Client",
    requestedDate: "2026-04-20",
    followUpDate: "2026-05-18",
    status: "Open",
    impact: "High",
    owner: "Zara Khan",
    notes: "Need to know the format before building the parser.",
  },
  {
    id: "bl4",
    title: "VPS SSH access for BuildRight not received",
    clientId: "cl5",
    clientName: "Construction Co.",
    projectId: "pr5",
    projectName: "BuildRight n8n Automation",
    whatIsBlocked: "n8n deployment and go-live",
    whatWeNeed: "Root SSH access or sudo user credentials for Hostinger VPS",
    neededFrom: "Client",
    requestedDate: "2026-05-08",
    followUpDate: "2026-05-22",
    status: "Open",
    impact: "High",
    owner: "Omar Farooq",
    notes: "James keeps saying he will send it. Need to escalate.",
    relatedAccessId: "ac5",
  },
];

// ─── DELIVERABLES ─────────────────────────────────────────────────────────────

export const deliverables: Deliverable[] = [
  {
    id: "d1",
    title: "OpenClaw Pipeline Architecture Doc",
    clientId: "cl1",
    clientName: "Tommy / Tongal",
    projectId: "pr1",
    projectName: "OpenClaw Lead Pipeline",
    type: "Documentation",
    status: "Sent",
    link: "https://docs.google.com/openclaw-arch",
    sentDate: "2026-04-20",
    notes: "Full architecture overview including data flow diagrams",
    createdAt: "2026-04-18",
  },
  {
    id: "d2",
    title: "Apollo Integration Live",
    clientId: "cl1",
    clientName: "Tommy / Tongal",
    projectId: "pr1",
    projectName: "OpenClaw Lead Pipeline",
    type: "Deployed URL",
    status: "Approved",
    link: "https://app.autoplay.ai/tongal-apollo",
    sentDate: "2026-04-30",
    approvedDate: "2026-05-02",
    notes: "Apollo pipeline live and processing",
    createdAt: "2026-04-28",
  },
  {
    id: "d3",
    title: "Supplier Email Test Report",
    clientId: "cl2",
    clientName: "Robert / Supplier Outreach",
    projectId: "pr2",
    projectName: "Supplier Email Automation",
    type: "Report",
    status: "Draft",
    notes: "Test results for 50-supplier email sequence",
    createdAt: "2026-05-16",
  },
  {
    id: "d4",
    title: "Telegram Bot Fleet - All 3 Bots Live",
    clientId: "cl4",
    clientName: "Frank / FrankBot",
    projectId: "pr4",
    projectName: "Telegram Bot Fleet",
    type: "Deployed URL",
    status: "Approved",
    link: "https://t.me/frankbot1",
    sentDate: "2026-05-10",
    approvedDate: "2026-05-12",
    notes: "All 3 bots confirmed live by Frank",
    createdAt: "2026-05-09",
  },
  {
    id: "d5",
    title: "FrankBot Handover Documentation",
    clientId: "cl4",
    clientName: "Frank / FrankBot",
    projectId: "pr4",
    projectName: "Telegram Bot Fleet",
    type: "Handover Docs",
    status: "Draft",
    notes: "In progress - admin panel guide and webhook docs",
    createdAt: "2026-05-14",
  },
  {
    id: "d6",
    title: "ScaleUp Kickoff Summary",
    clientId: "cl6",
    clientName: "Dean / ScaleUp",
    projectId: "pr6",
    projectName: "ScaleUp Lead Gen Setup",
    type: "Documentation",
    status: "Sent",
    link: "https://docs.google.com/scaleup-kickoff",
    sentDate: "2026-05-16",
    notes: "ICP definition, project roadmap, tool list",
    createdAt: "2026-05-15",
  },
];

// ─── APPROVALS ───────────────────────────────────────────────────────────────

export const approvals: Approval[] = [
  {
    id: "ap1",
    title: "OpenClaw Project Scope Approval",
    type: "Scope approval",
    clientId: "cl1",
    clientName: "Tommy / Tongal",
    projectId: "pr1",
    status: "Approved",
    submittedDate: "2026-03-05",
    resolvedDate: "2026-03-07",
    requestedBy: "Nouman Ejaz",
    notes: "Approved without changes",
  },
  {
    id: "ap2",
    title: "Telegram Bot Final Design Approval",
    type: "Design/content approval",
    clientId: "cl4",
    clientName: "Frank / FrankBot",
    projectId: "pr4",
    status: "Approved",
    submittedDate: "2026-05-08",
    resolvedDate: "2026-05-10",
    requestedBy: "Bilal Siddiqui",
    notes: "Frank approved all 3 bot designs",
  },
  {
    id: "ap3",
    title: "Supplier Email Copy Approval",
    type: "Design/content approval",
    clientId: "cl2",
    clientName: "Robert / Supplier Outreach",
    projectId: "pr2",
    status: "Changes Requested",
    submittedDate: "2026-05-10",
    requestedBy: "Nouman Ejaz",
    notes: "Robert wants softer tone in subject lines. Revision in progress.",
  },
  {
    id: "ap4",
    title: "ScaleUp Project Scope",
    type: "Scope approval",
    clientId: "cl6",
    clientName: "Dean / ScaleUp",
    projectId: "pr6",
    status: "Under Review",
    submittedDate: "2026-05-16",
    requestedBy: "Nouman Ejaz",
    notes: "Awaiting Dean's review",
  },
];

// ─── TIMELINE ENTRIES ─────────────────────────────────────────────────────────

export const timelineEntries: TimelineEntry[] = [
  {
    id: "te1",
    clientId: "cl1",
    type: "status_change",
    person: "Nouman Ejaz",
    date: "2026-05-16",
    description: "Project status updated to Active. OpenClaw gateway fully verified.",
    projectId: "pr1",
    visibility: "Internal",
  },
  {
    id: "te2",
    clientId: "cl1",
    type: "ai_summary",
    person: "Autoplay AI",
    date: "2026-05-15",
    description:
      "Today we completed the OpenClaw gateway verification, tested Apollo connectivity, and confirmed the data ingestion pipeline is operational. The only pending item is final LinkedIn Sales Navigator access from Tommy.",
    projectId: "pr1",
    visibility: "Internal",
  },
  {
    id: "te3",
    clientId: "cl1",
    type: "blocker_update",
    person: "Nouman Ejaz",
    date: "2026-05-14",
    description: "Followed up with Tommy on LinkedIn access via WhatsApp. Third follow-up sent.",
    projectId: "pr1",
    visibility: "Internal",
  },
  {
    id: "te4",
    clientId: "cl2",
    type: "delivered",
    person: "Nouman Ejaz",
    date: "2026-05-15",
    description: "Sent weekly update to Robert. Testing phase in progress. Go-live on track for May 31.",
    projectId: "pr2",
    visibility: "Client-visible",
  },
  {
    id: "te5",
    clientId: "cl3",
    type: "follow_up",
    person: "Zara Khan",
    date: "2026-05-14",
    description: "Emailed Dr. Steve again about SMTP credentials. No response in 2 weeks. Escalation recommended.",
    projectId: "pr3",
    visibility: "Internal",
  },
  {
    id: "te6",
    clientId: "cl4",
    type: "delivered",
    person: "Bilal Siddiqui",
    date: "2026-05-12",
    description: "All 3 Telegram bots confirmed live by Frank. Webhook delivery 100% operational.",
    projectId: "pr4",
    visibility: "Client-visible",
  },
  {
    id: "te7",
    clientId: "cl6",
    type: "meeting_note",
    person: "Nouman Ejaz",
    date: "2026-05-15",
    description: "Kickoff call with Dean completed. ICP defined: B2B SaaS companies 10-50 employees. Budget $500/m for tools. Timelines agreed.",
    projectId: "pr6",
    visibility: "Internal",
  },
];

// ─── AI SUMMARIES ─────────────────────────────────────────────────────────────

export const aiSummaries: AISummary[] = [
  {
    id: "ai1",
    clientId: "cl1",
    clientName: "Tommy / Tongal",
    projectId: "pr1",
    type: "client_update",
    content:
      "Hi Tommy,\n\nHere's a quick update on the OpenClaw pipeline:\n\n✅ OpenClaw gateway is fully verified and operational\n✅ Apollo.io integration is live and processing leads\n✅ Data ingestion pipeline is tested and stable\n\n⏳ The only outstanding item is the LinkedIn Sales Navigator access. Once we receive this, we can complete the final lead export step and deliver the full pipeline.\n\nWe're on track for the June 15 deadline once we get that access sorted. Please do let us know if you need any support getting that set up!\n\nBest,\nAutoplay Team",
    generatedAt: "2026-05-15T10:30:00",
    generatedBy: "Autoplay AI",
  },
  {
    id: "ai2",
    clientId: "cl4",
    clientName: "Frank / FrankBot",
    projectId: "pr4",
    type: "weekly_report",
    content:
      "Weekly Progress Report — FrankBot Telegram Fleet\n\nThis week we achieved major milestones on the FrankBot project:\n\n• All 3 Telegram bots are deployed and live in production\n• Webhook delivery pipeline tested — 100% delivery rate confirmed\n• Admin panel build is 85% complete\n• Handover documentation started\n\nRemaining work (est. 8 hours):\n• Complete admin panel UI polish\n• Finalize handover documentation\n• Conduct client walkthrough session\n• Obtain final deployment approval\n\nProject is on track for May 30 completion.",
    generatedAt: "2026-05-17T09:00:00",
    generatedBy: "Autoplay AI",
  },
  {
    id: "ai3",
    clientId: "cl3",
    clientName: "Dr. Steve / MedReach",
    projectId: "pr3",
    type: "needs_from_client",
    content:
      "What We Need From Dr. Steve — MedReach Email System\n\nTo proceed with the email system build, we urgently need the following from your side:\n\n🔴 CRITICAL:\n1. SMTP credentials (host, port, username, password) — Blocked since April 15\n2. Sample patient data export or CRM API documentation\n\n🟡 IMPORTANT:\n3. Compliance sign-off on patient communication templates\n4. Confirmation of preferred sending volume (emails/day)\n\nWithout items 1 and 2, we cannot proceed with any technical work. The project is currently on hold and at risk of missing the June 30 deadline.",
    generatedAt: "2026-05-14T14:00:00",
    generatedBy: "Autoplay AI",
  },
];

// ─── COMPUTED STATS ───────────────────────────────────────────────────────────

export function getDashboardStats() {
  const activeClients = clients.filter((c) => c.status === "Active").length;
  const activeProjects = projects.filter((p) => p.status === "Active").length;
  const openBlockers = blockers.filter((b) => b.status === "Open").length;
  const totalHoursThisWeek = timeLogs
    .filter((t) => {
      const d = new Date(t.date);
      const now = new Date();
      const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
      return d >= weekAgo;
    })
    .reduce((sum, t) => sum + t.hours, 0);
  const completedDeliverables = deliverables.filter((d) => d.status === "Approved").length;
  const tasksDueThisWeek = tasks.filter((t) => {
    const d = new Date(t.dueDate);
    const now = new Date();
    const weekOut = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
    return d <= weekOut && t.status !== "Completed";
  }).length;
  const waitingOnClient = blockers.filter(
    (b) => b.neededFrom === "Client" && b.status === "Open"
  ).length;
  const accessPending = accessItems.filter(
    (a) => a.status === "Pending" || a.status === "Need Client Action"
  ).length;

  return {
    activeClients,
    activeProjects,
    openBlockers,
    totalHoursThisWeek,
    completedDeliverables,
    tasksDueThisWeek,
    waitingOnClient,
    accessPending,
  };
}

export function getClientById(id: string) {
  return clients.find((c) => c.id === id);
}

export function getProjectsByClient(clientId: string) {
  return projects.filter((p) => p.clientId === clientId);
}

export function getTasksByClient(clientId: string) {
  return tasks.filter((t) => t.clientId === clientId);
}

export function getBlockersByClient(clientId: string) {
  return blockers.filter((b) => b.clientId === clientId);
}

export function getAssetsByClient(clientId: string) {
  return assets.filter((a) => a.clientId === clientId);
}

export function getAccessByClient(clientId: string) {
  return accessItems.filter((a) => a.clientId === clientId);
}

export function getTimelineByClient(clientId: string) {
  return timelineEntries.filter((t) => t.clientId === clientId);
}

export function getDeliverablesByClient(clientId: string) {
  return deliverables.filter((d) => d.clientId === clientId);
}

export function getApprovalsByClient(clientId: string) {
  return approvals.filter((a) => a.clientId === clientId);
}

export function getAISummariesByClient(clientId: string) {
  return aiSummaries.filter((s) => s.clientId === clientId);
}
